print("hello")#string
x=10
print(x)#int
y=20.5
print(y)#float
z=1j
print(z)#complex
a=["apple","banana","mango"]
print(a)#list
b=("apple","banana","mango")
print(b)#tuple
c=range(6)
print(c)#range
d={"name":"khushi","age":18}
print(d)#dict
e={"apple","banana","mango"}
print(e)#set"""
f=frozenset({"apple","banana","mango"})
print(f)#frozenset
g=True
print(g)#bool
h=b"hello"
print(h)#bytes
i=bytearray(5)
print(i)#bytearray
j=memoryview(bytes(5))
print(j)#memoryview
k=None
print(k)#None type 